# env variable

DEFAULT_PORT = 7777
DEFAULT_IP_ADDRESS = '127.0.0.1'
MAX_CONNECTIONS = 5
MAX_PACKET_LENGTH = 1024
ENCODING = 'utf-8'
ACTION = 'action'
TIME = 'time'
CONNECTION_TIMEOUT = 0.5
USER = 'user'
ACCOUNT_NAME = 'account_name'
PRESENCE = 'presence'
RESPONSE = 'response'
ERROR = 'error'
MESSAGE = 'msg'
MESSAGE_TEXT = 'message'
SENDER = 'sender'
DESTINATION = 'to'
EXIT = 'exit'
